# Generated by Django 5.0.3 on 2024-03-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
