# Generated by Django 5.0.3 on 2024-03-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
