# Generated by Django 5.0.3 on 2024-03-26 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='employee',
            name='lname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
