# Generated by Django 5.0.3 on 2024-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0004_rename_name_employee_fname_employee_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='grosspay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
