# Generated by Django 5.0.3 on 2024-04-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0008_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
